export default {
  kernelVersion: '41.2',
  kernelPath:    'kernel',
  testsPath:     'kernel/tests',
  klPath:        'kernel/klambda',
  klExt:         '.kl',
  klFiles: [
    'compiler',
    'toplevel',
    'core',
    'sys',
    'dict',
    'sequent',
    'yacc',
    'reader',
    'prolog',
    'track',
    'load',
    'writer',
    'macros',
    'declarations',
    'types',
    't-star',
    'init',
    'extension-features',
    'extension-expand-dynamic',
    'extension-launcher',
    'stlib'
  ]
};
